spring:
  datasource:
    username: inmon
    password: jhsz0603
    url: jdbc:oracle:thin:@10.0.0.100:1521:edw
    driver: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20