spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.15.128:3306/jdbc
    driver: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20